Nhóm 3:
Nguyễn Văn Hiếu,
Nguyễn Hoàng Tuấn,
Trần Thị Diễm Quỳnh,
Võ Thị Thúy Sa


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

### **tensorflow**

1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0


In [ ]:
cau1=tf.zeros([2,3])
print(cau1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
mang=tf.random.uniform([200],5,10,dtype=tf.int32)
cau4=tf.boolean_mask(mang,mang % 2==0)

print(cau4[:50])

tf.Tensor(
[8 6 6 8 6 8 8 8 8 8 6 8 6 6 8 8 6 6 8 8 8 8 8 8 8 8 6 6 8 8 8 6 8 6 8 6 6
 6 6 6 8 8 8 6 8 6 6 6 6 6], shape=(50,), dtype=int32)


5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, ..., 100]

In [ ]:
mang=tf.range(10,101,2,dtype=tf.int32)
print(mang)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


**8**. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng random_shuffle)

In [ ]:
X=tf.constant([[1, 2], [3, 4], [5, 6]])

tf_sf=tf.random.shuffle(X)
print(tf_sf)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x <  y, và x – y nếu x > y

In [ ]:
x = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
result = tf.where(x<y,x+y,x-y)
print("Tensor x:")
print(x)
print("Tensor y:")
print(y)
print("Kết quả x + y hoặc x - y:")
print(result)

Tensor x:
tf.Tensor([7 0 3 6 7], shape=(5,), dtype=int32)
Tensor y:
tf.Tensor([4 0 1 6 0], shape=(5,), dtype=int32)
Kết quả x + y hoặc x - y:
tf.Tensor([3 0 2 0 7], shape=(5,), dtype=int32)


9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử dụng random_crop)

In [ ]:
import tensorflow as tf

# Tạo một tensor ngẫu nhiên kích thước (10, 10, 3)
tensor = tf.random.uniform([10, 10, 3], minval=0, maxval=255, dtype=tf.int32)

# Sử dụng random_crop để cắt một phần tensor với kích thước (5, 5, 3)
cropped_tensor = tf.image.random_crop(tensor, size=[5, 5, 3])

# In kết quả
print("Tensor ban đầu (10, 10, 3):")
print(tensor.numpy())
print("\nTensor sau khi cắt (5, 5, 3):")
print(cropped_tensor.numpy())


Tensor ban đầu (10, 10, 3):
[[[ 26  19 192]
  [170  89  54]
  [186  20 227]
  [140 205  86]
  [240 183 218]
  [113  21 252]
  [163  76  39]
  [ 64  41 212]
  [ 20  84 223]
  [ 32  68 152]]

 [[178   0 237]
  [ 92 152 206]
  [ 18 135 223]
  [ 52  67  35]
  [ 65 110 205]
  [188  65  97]
  [ 72 165 185]
  [ 19 180 176]
  [196 101   7]
  [192 174 156]]

 [[ 62 178  35]
  [254  13 166]
  [194 207 165]
  [ 12 215  51]
  [109  31  24]
  [183 222 120]
  [ 91  96 156]
  [162 208  28]
  [180 204 242]
  [136 206 220]]

 [[ 37 129  72]
  [ 43  53  74]
  [116  60 166]
  [ 67  41 237]
  [ 38  19  53]
  [ 22 110 211]
  [140   2 219]
  [159 113 233]
  [ 49 106  42]
  [  6 241 128]]

 [[145  88  17]
  [ 76  50 254]
  [ 32 189  98]
  [242 188 152]
  [231  64 228]
  [ 14 206  88]
  [ 94 113 135]
  [200 207 218]
  [159  80 177]
  [170  14 238]]

 [[111  45  55]
  [201  47 226]
  [ 48  73  93]
  [208 167  37]
  [ 25 103 196]
  [146 229 107]
  [ 94 155 229]
  [160 191 196]
  [137 221 156]
  [ 87  50 240]]



**Câu 11-15 Lab 1 TensorFlow**
```
11. Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.
12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng, trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.
13. Xây dựng model để tính tổng hai tensor x, y
14. Xây dựng model để tính hiệu và tích hai tensor x, y
15. Xây dựng model để tính chu vi hình chữ nhật P = (a +b) * 2
```

In [ ]:
# 11. Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.
x = tf.random.uniform(shape=(3, 2), minval=5, maxval=10, dtype=tf.float32)
y = tf.random.uniform(shape=(2, 3), minval=15, maxval=20, dtype=tf.float32)
# Chuyển vị y để có kích thước (3, 2)
y_transposed = tf.transpose(y)
# Thực hiện phép cộng
z = x + y_transposed

# Lấy đường chéo của x
diag_x = tf.linalg.diag_part(x)
# Thay thế đường chéo của z bằng đường chéo của x
result = tf.linalg.set_diag(z, diag_x)
try:
  print("Tensor x:\n", x.numpy())
  print("Tensor y:\n", y.numpy())
  print("Tensor y sau khi chuyển vị:\n", y_transposed.numpy())
  print("Kết quả trước khi giữ đường chéo:\n", z.numpy())
  print("Kết quả cuối cùng:\n", result.numpy())
except tf.errors.InvalidArgumentError as e:
  print(f"Error: {e}\n")
  print("Tensor shapes are incompatible for addition.")

Tensor x:
 [[8.231576  5.2843924]
 [9.043267  7.244556 ]
 [6.933977  8.225766 ]]
Tensor y:
 [[18.047905  15.2969475 19.102852 ]
 [15.109225  19.621153  16.32601  ]]
Tensor y sau khi chuyển vị:
 [[18.047905  15.109225 ]
 [15.2969475 19.621153 ]
 [19.102852  16.32601  ]]
Kết quả trước khi giữ đường chéo:
 [[26.27948  20.393618]
 [24.340214 26.86571 ]
 [26.036829 24.551777]]
Kết quả cuối cùng:
 [[ 8.231576 20.393618]
 [24.340214  7.244556]
 [26.036829 24.551777]]


In [ ]:
# 12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng,trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.
# 1. Hàm tạo tensor ngẫu nhiên
def create_tensors():
    """Tạo 2 tensor x, y kích thước (3, 2, 2) với giá trị ngẫu nhiên [0, 1)"""
    x = tf.random.uniform(shape=(3, 2, 2))
    y = tf.random.uniform(shape=(3, 2, 2))
    return x, y

# 2. Định nghĩa các phép toán dưới dạng graph
@tf.function
def tensor_add(x, y):
  """Phép cộng phần tử"""
  return tf.add(x, y, name="Addition")

@tf.function
def tensor_sub(x, y):
  """Phép trừ phần tử"""
  return tf.subtract(x, y, name="Subtraction")

@tf.function
def tensor_mul(x, y):
  """Phép nhân phần tử"""
  return tf.multiply(x, y, name="Multiplication")

@tf.function
def tensor_div(x, y):
  """Phép chia phần tử"""
  return tf.divide(x, y, name="Division")

# 3. Thực thi và kiểm tra
if __name__ == "__main__":
  # Tạo tensor
  x, y = create_tensors()

  # Thực hiện các phép toán
  add_result = tensor_add(x, y)
  sub_result = tensor_sub(x, y)
  mul_result = tensor_mul(x, y)
  div_result = tensor_div(x, y)

  # In kết quả
  print("Input x:\n", x.numpy())
  print("\nInput y:\n", y.numpy())
  print("\nAddition result:\n", add_result.numpy())
  print("\nSubtraction result:\n", sub_result.numpy())
  print("\nMultiplication result:\n", mul_result.numpy())
  print("\nDivision result:\n", div_result.numpy())

print(tensor_add.pretty_printed_concrete_signatures())

def safe_div(x, y):
  return tf.where(y == 0, 0, x/y)

Input x:
 [[[0.6208296  0.78402364]
  [0.10202277 0.73092604]]

 [[0.22917914 0.05647933]
  [0.7560961  0.37713838]]

 [[0.16732752 0.7617289 ]
  [0.97927475 0.93434453]]]

Input y:
 [[[0.26484168 0.8926985 ]
  [0.489537   0.15247321]]

 [[0.5287827  0.42967415]
  [0.37232625 0.5465344 ]]

 [[0.12305737 0.77437806]
  [0.00570619 0.73387134]]]

Addition result:
 [[[0.88567126 1.6767222 ]
  [0.59155977 0.88339925]]

 [[0.75796187 0.48615348]
  [1.1284224  0.9236728 ]]

 [[0.2903849  1.536107  ]
  [0.98498094 1.6682159 ]]]

Subtraction result:
 [[[ 0.3559879  -0.10867488]
  [-0.38751423  0.5784528 ]]

 [[-0.29960358 -0.3731948 ]
  [ 0.38376987 -0.16939604]]

 [[ 0.04427016 -0.01264918]
  [ 0.97356856  0.20047319]]]

Multiplication result:
 [[[0.16442154 0.69989675]
  [0.04994392 0.11144664]]

 [[0.12118597 0.02426771]
  [0.28151444 0.2061191 ]]

 [[0.02059088 0.58986616]
  [0.00558793 0.6856887 ]]]

Division result:
 [[[2.3441536e+00 8.7826252e-01]
  [2.0840666e-01 4.7937999e+00]]

 [[4.3

In [ ]:
# 13. Xây dựng model để tính tổng hai tensor x, y
# 1. Định nghĩa model
def build_sum_model(input_shape):
  """Xây dựng model tính tổng hai tensor cùng kích thước"""
  # Định nghĩa hai input layer
  input_x = tf.keras.Input(shape=input_shape, name='input_x')
  input_y = tf.keras.Input(shape=input_shape, name='input_y')

  # Layer cộng hai tensor
  sum_layer = tf.keras.layers.Add(name='addition_layer')([input_x, input_y])

  # Tạo model
  model = tf.keras.Model(
    inputs=[input_x, input_y],
    outputs=sum_layer,
    name='Sum_Model'
  )
  return model

# 2. Tạo và sử dụng model
if __name__ == "__main__":
  # Giả sử tensor có shape (2, 2) - có thể thay đổi theo yêu cầu
  input_shape = (2, 2)

  # Khởi tạo model
  model = build_sum_model(input_shape)

  # Tạo dữ liệu test
  x = tf.constant([[1., 2.], [3., 4.]])  # Shape (2,2)
  y = tf.constant([[5., 6.], [7., 8.]])  # Shape (2,2)

  # Dự đoán kết quả
  result = model.predict([x[tf.newaxis], y[tf.newaxis]])

  # In thông tin model và kết quả
  model.summary()
  print("\nInput x:\n", x.numpy())
  print("\nInput y:\n", y.numpy())
  print("\nSum result:\n", result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


Model: "Sum_Model"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_x             │ (None, 2, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_y             │ (None, 2, 2)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ addition_layer      │ (None, 2, 2)      │          0 │ input_x[0][0],    │
│ (Add)               │                   │            │ input_y[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


Input x:
 [[1. 2.]
 [3. 4.]]

Input y:
 [[5. 6.]
 [7. 8.]]

Sum result:
 [[[ 6.  8.]
  [10. 12.]]]


In [ ]:
# 14. Xây dựng model để tính hiệu và tích hai tensor x, y
def diff_product_model(x, y):
  diff = tf.subtract(x, y)
  product = tf.multiply(x, y)
  return diff, product



diff_res, product_res = diff_product_model(x, y)
print("Difference:", diff_res)
print("Product:", product_res)

Difference: tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
Product: tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [ ]:
# 15. Xây dựng model để tính chu vi hình chữ nhật P = (a +b) * 2
def rectangle_perimeter(a, b):
  perimeter = (a + b) * 2
  return perimeter



a = tf.constant(5.0)
b = tf.constant(10.0)
perimeter = rectangle_perimeter(a, b)
print("Perimeter:", perimeter)

Perimeter: tf.Tensor(30.0, shape=(), dtype=float32)


**7CAU NUMPY**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

  #Bai1:Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viếtchương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)
arr = np.random.randint(0, 21, size=(3, 3))
print("Mảng tạo ra:")
print(arr)
tat_ca_khac_0 = np.all(arr != 0)
print("\nTất cả phần tử đều khác 0:", tat_ca_khac_0)

  #Bai2 : Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viếtchương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)
arr_raw = np.random.randint(0, 21, size=20)
arr = arr_raw[:9].reshape((3, 3))
print("Mảng 3x3 tạo ra:")
print(arr)
ton_tai_khac_0 = np.any(arr != 0)
print("\nTồn tại ít nhất một phần tử khác 0:", ton_tai_khac_0)

  #Bai3:Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
ones = np.ones(10, dtype=int)
zeros = np.zeros(10, dtype=int)
fives = np.full(10, 5)
result = np.concatenate([ones, zeros, fives])
print("Mảng kết quả gồm 10 số 1, 10 số 0 và 10 số 5:")
print(result)

  #Bai4:  Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

even_numbers = np.arange(30, 71, 2)
print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_numbers)
  #Bai 5:Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tửđầu và cuối
arr = np.random.randint(15, 56, size=10)
print("Mảng ngẫu nhiên:")
print(arr)
print("\nMảng sau khi bỏ phần tử đầu và cuối:")
print(arr[1:-1])
  #Bai6 :Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sumcủa numpy)
arr = np.random.randint(0, 11, size=(3, 3, 3))
print("Mảng 3x3x3:")
print(arr)
tong_theo_dong = np.sum(arr, axis=1)
print("\nTổng theo từng dòng (axis=1):")
print(tong_theo_dong)
tong_theo_cot = np.sum(arr, axis=2)
print("\nTổng theo từng cột (axis=2):")
print(tong_theo_cot)
 # Bai 7 : Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong cógiá trị 0
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix)




[1 2 3]
Mảng tạo ra:
[[14  0 13]
 [ 5  3 19]
 [15 10  6]]

Tất cả phần tử đều khác 0: False
Mảng 3x3 tạo ra:
[[ 1 11  0]
 [ 6  2 20]
 [20 10 20]]

Tồn tại ít nhất một phần tử khác 0: True
Mảng kết quả gồm 10 số 1, 10 số 0 và 10 số 5:
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]
Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
Mảng ngẫu nhiên:
[23 52 42 29 30 19 48 34 42 39]

Mảng sau khi bỏ phần tử đầu và cuối:
[52 42 29 30 19 48 34 42]
Mảng 3x3x3:
[[[ 1  0  0]
  [ 1  9 10]
  [10  2  3]]

 [[ 5  5  4]
  [ 2  4  9]
  [ 6  9  2]]

 [[ 7  4  6]
  [ 9  6  3]
  [ 9  6  5]]]

Tổng theo từng dòng (axis=1):
[[12 11 13]
 [13 18 15]
 [25 16 14]]

Tổng theo từng cột (axis=2):
[[ 1 20 15]
 [14 15 17]
 [17 18 20]]
Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 

**Pandas**

In [ ]:
#16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series
#(Tìm hiểu thuộc tính ix của pandas)
import pandas as pd
data = {
        'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]
      }
df = pd.DataFrame(data)
c1 = df.iloc[:, 0] # : Lấy all dòng, 0 là cột đầu
print('1st column as a Series:')
print(c1)

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [ ]:
#18. Viết chương trình Pandas thay đổi index của một Series
#(dùng pandas.reindex)
import pandas as pd
data = pd.Series([1, 2, 3, 4, 5], index = ['A', 'B', 'C', 'D', 'E'])
print(data)

print('Data Series after changing the order of index:')
new_data = data.reindex(index = ['B', 'A', 'C', 'D', 'E'])
print(new_data)

A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [ ]:
#19.Viết chương trình Pandas tìm những phần tử trong Series x
# mà không có trong Series y (Tìm hiểu hàm isin của pandas)
import pandas as pd
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print('sr1:')
print(sr1)
print('sr2:')
print(sr2)
print('sr1 - sr2:')
result = sr1[~sr1.isin(sr2)] #Lọc phần tử ko nằm trong sr2
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64
sr1 - sr2:
0    1
2    3
4    5
dtype: int64


In [ ]:
#20. Tìm hiểu phép toán numpy.union1d, numpy.intersect1d (hội, giao) và viết
#chương trình minh họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử
import numpy as np
import pandas as pd
x = pd.Series(np.random.randint(1, 10, 20))
y = pd.Series(np.random.randint(1, 10, 20))
uni_result = np.union1d(x, y)
inter_result = np.intersect1d(x, y)
print('Union result:')
print(uni_result)
print('Intersection result:')
print(x)
print(y)

Union result:
[1 2 3 4 5 6 7 8 9]
Intersection result:
0     7
1     1
2     4
3     2
4     1
5     4
6     2
7     8
8     2
9     5
10    8
11    8
12    1
13    3
14    8
15    8
16    7
17    9
18    3
19    6
dtype: int64
0     9
1     8
2     4
3     1
4     2
5     5
6     5
7     5
8     1
9     5
10    3
11    9
12    2
13    4
14    5
15    9
16    7
17    8
18    7
19    5
dtype: int64


In [ ]:
#22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame sau
# exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
#                       'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
# 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
# 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
# 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
# labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                      'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index = labels)
print(df)

print('\n')
#23. Từ bài 22, cho biết 3 dòng đầu tiên
print('3 dòng đầu tiên:')
print(df.head(3))

print('\n')
#28. Từ bài 22, cho biết những dòng có score trong khoảng (15, 20)
# (tìm hiểu hàm between của pandas)
print('Dòng có score trong khoảng (15, 20):')
print(df[df['score'].between(15, 20)])

print('\n')
#29. Từ bài 22, cho biết những dòng có attempt >2 và score trong khoảng (15, 20)
print('Dòng có attemp > 2:')
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


3 dòng đầu tiên:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


Dòng có score trong khoảng (15, 20):
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


Dòng có attemp > 2:
      name  score  attempts qualify
f  Michael   20.0         3     yes
